package vn.framgia.model;
// Generated Nov 15, 2018 2:38:22 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private Integer accountId;
	private Branch branch;
	private Customer customer;
	private Employee employee;
	private Product product;
	private Float availBalance;
	private Date closeDate;
	private Date lastActivityDate;
	private Date openDate;
	private Float pendingBalance;
	private String status;
	private Set accTransactions = new HashSet(0);

	public Account() {
	}

	public Account(Branch branch, Employee employee, Product product, Date openDate) {
		this.branch = branch;
		this.employee = employee;
		this.product = product;
		this.openDate = openDate;
	}

	public Account(Branch branch, Customer customer, Employee employee, Product product, Float availBalance,
			Date closeDate, Date lastActivityDate, Date openDate, Float pendingBalance, String status,
			Set accTransactions) {
		this.branch = branch;
		this.customer = customer;
		this.employee = employee;
		this.product = product;
		this.availBalance = availBalance;
		this.closeDate = closeDate;
		this.lastActivityDate = lastActivityDate;
		this.openDate = openDate;
		this.pendingBalance = pendingBalance;
		this.status = status;
		this.accTransactions = accTransactions;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Float getAvailBalance() {
		return this.availBalance;
	}

	public void setAvailBalance(Float availBalance) {
		this.availBalance = availBalance;
	}

	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	public Date getLastActivityDate() {
		return this.lastActivityDate;
	}

	public void setLastActivityDate(Date lastActivityDate) {
		this.lastActivityDate = lastActivityDate;
	}

	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	public Float getPendingBalance() {
		return this.pendingBalance;
	}

	public void setPendingBalance(Float pendingBalance) {
		this.pendingBalance = pendingBalance;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getAccTransactions() {
		return this.accTransactions;
	}

	public void setAccTransactions(Set accTransactions) {
		this.accTransactions = accTransactions;
	}

}
