package vn.framgia.model;
// Generated Nov 15, 2018 2:38:22 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch implements java.io.Serializable {

	private Integer branchId;
	private String address;
	private String city;
	private String name;
	private String state;
	private String zipCode;
	private Set accounts = new HashSet(0);
	private Set accTransactions = new HashSet(0);
	private Set employees = new HashSet(0);

	public Branch() {
	}

	public Branch(String name) {
		this.name = name;
	}

	public Branch(String address, String city, String name, String state, String zipCode, Set accounts,
			Set accTransactions, Set employees) {
		this.address = address;
		this.city = city;
		this.name = name;
		this.state = state;
		this.zipCode = zipCode;
		this.accounts = accounts;
		this.accTransactions = accTransactions;
		this.employees = employees;
	}

	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

	public Set getAccTransactions() {
		return this.accTransactions;
	}

	public void setAccTransactions(Set accTransactions) {
		this.accTransactions = accTransactions;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
