package vn.framgia.model;
// Generated Nov 15, 2018 2:38:22 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Business generated by hbm2java
 */
public class Business implements java.io.Serializable {

	private int custId;
	private Customer customer;
	private Date incorpDate;
	private String name;
	private String stateId;

	public Business() {
	}

	public Business(Customer customer, String name, String stateId) {
		this.customer = customer;
		this.name = name;
		this.stateId = stateId;
	}

	public Business(Customer customer, Date incorpDate, String name, String stateId) {
		this.customer = customer;
		this.incorpDate = incorpDate;
		this.name = name;
		this.stateId = stateId;
	}

	public int getCustId() {
		return this.custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getIncorpDate() {
		return this.incorpDate;
	}

	public void setIncorpDate(Date incorpDate) {
		this.incorpDate = incorpDate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStateId() {
		return this.stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

}
