package vn.framgia.model;
// Generated Nov 15, 2018 2:38:22 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer custId;
	private String address;
	private String city;
	private String custTypeCd;
	private String fedId;
	private String postalCode;
	private String state;
	private Individual individual;
	private Business business;
	private Set accounts = new HashSet(0);
	private Set officers = new HashSet(0);

	public Customer() {
	}

	public Customer(String custTypeCd, String fedId) {
		this.custTypeCd = custTypeCd;
		this.fedId = fedId;
	}

	public Customer(String address, String city, String custTypeCd, String fedId, String postalCode, String state,
			Individual individual, Business business, Set accounts, Set officers) {
		this.address = address;
		this.city = city;
		this.custTypeCd = custTypeCd;
		this.fedId = fedId;
		this.postalCode = postalCode;
		this.state = state;
		this.individual = individual;
		this.business = business;
		this.accounts = accounts;
		this.officers = officers;
	}

	public Integer getCustId() {
		return this.custId;
	}

	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCustTypeCd() {
		return this.custTypeCd;
	}

	public void setCustTypeCd(String custTypeCd) {
		this.custTypeCd = custTypeCd;
	}

	public String getFedId() {
		return this.fedId;
	}

	public void setFedId(String fedId) {
		this.fedId = fedId;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Individual getIndividual() {
		return this.individual;
	}

	public void setIndividual(Individual individual) {
		this.individual = individual;
	}

	public Business getBusiness() {
		return this.business;
	}

	public void setBusiness(Business business) {
		this.business = business;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

	public Set getOfficers() {
		return this.officers;
	}

	public void setOfficers(Set officers) {
		this.officers = officers;
	}

}
