package vn.framgia.model;
// Generated Nov 15, 2018 2:38:22 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProductType generated by hbm2java
 */
public class ProductType implements java.io.Serializable {

	private String productTypeCd;
	private String name;
	private Set products = new HashSet(0);

	public ProductType() {
	}

	public ProductType(String productTypeCd) {
		this.productTypeCd = productTypeCd;
	}

	public ProductType(String productTypeCd, String name, Set products) {
		this.productTypeCd = productTypeCd;
		this.name = name;
		this.products = products;
	}

	public String getProductTypeCd() {
		return this.productTypeCd;
	}

	public void setProductTypeCd(String productTypeCd) {
		this.productTypeCd = productTypeCd;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
